### ISSUE TITLE
Missing: your Azure Spatial Anchors ebook

### ISSUE THREAD

**Issue by joshuaalm** [Yonet/MixedRealityResources#1]
I don't see the book you presented at MIT Reality Hack and I was looking forward to reading it again.  Please update with any other works you have posted that are relevant to MR.

**Comment by Yonet** [comment]
Good catch @joshuaalm, I am glad you are planning to read it again. I will extend it soon. Please let me know if there is anything that doesn't make sense.

Here is the link: aka.ms/AzureSpatialAnchorsLesson
